language: python
python:
  - "3.7-dev"

script:
  - pytest

deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  file: dist/an-python-scripts-0.1.0.tar.gz
  skip_cleanup: true
  on:
    tags: true