language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

jobs:
  include:
    - script: python -m unittest discover -s tests -p test_*.py
    - stage: deploy
      python: "3.7-dev"
      script: python setup.py sdist
      deploy:
        provider: releases
        api_key: ${GITHUB_OAUTH_TOKEN}
        file: dist/an-python-scripts-0.1.0.tar.gz
        skip_cleanup: true
        on:
          tags: true
          branch: master

stages:
  - test
  - name : deploy
    if: branch = master
