language: python
python:
  - "3.5"
  - "3.6-dev"
  - "3.7-dev"

install: true
script: python -m unittest discover -s tests -p test_*.py

jobs:
  include:
    - stage: coverage
      python: "3.7-dev"
      install: pip install codecov
      script: coverage run --source app setup.py test
      after_success: codecov
    - stage: packaging
      python: "3.7-dev"
      install: true
      script: python setup.py sdist
      deploy:
        provider: releases
        api_key: ${GITHUB_OAUTH_TOKEN}
        file: dist/an-python-scripts-0.1.0.tar.gz
        skip_cleanup: true
        on:
          tags: true
          branch: master


stages:
  - test
  - coverage
  - name: packaging
    if: branch = master