version: 2.1
jobs:
  build:
    working_directory: ~/an-python-scripts

    docker:
      - image: circleci/python:3.7.3

    steps:
      - checkout
      - run:
          name: Python Build
          command: python setup.py sdist
      - run:
          name: Python Tests
          command: python -m unittest discover -s tests -p test_*.py

workflows:
  version: 2
  build:
    jobs:
      - build